#!/usr/bin/env bash

#установка asciidoctor
#gem install asciidoctor
#установка pandoc
#brew install pandoc
#установка pandoc в Windows https://github.com/jgm/pandoc/releases/latest

INPUT_ADOC=$1
asciidoctor --backend docbook --out-file - $INPUT_ADOC.adoc|pandoc --from docbook --to docx --output $INPUT_ADOC.docx