#!/usr/bin/env bash

#установка asciidoctor
#gem install asciidoctor
#установка pandoc
#brew install pandoc
#установка pandoc в Windows https://github.com/jgm/pandoc/releases/latest

INPUT_ADOC=$1
asciidoctor --backend docbook -o$INPUT_ADOC.adoc|pandoc --from docbook --to docx --output $INPUT_ADOC.docx
asciidoctor -s -C -a toc -o$INPUT_ADOC.html $INPUT_ADOC.adoc
asciidoctor-pdf -a toc -o$INPUT_ADOC.pdf $INPUT_ADOC.adoc